version: "3.9"

services:
  postgres:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql-dev/data
  apphost:
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development