services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-default-net
  apphost:
    build:
      context: .
      dockerfile: src/API/AppHost/Dockerfile
    restart: always
    depends_on:
      - postgres
    expose:
      - "8080"
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    networks:
      - app-default-net
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./proxy/ssl:/etc/nginx/ssl:ro
    depends_on:
      - apphost
    networks:
      - app-default-net
  frontend:
    image: nginx:alpine
    restart: always
    expose:
      - "80"
    volumes:
      - ./stub:/usr/share/nginx/html:ro
    networks:
      - app-default-net
      
volumes:
  postgres_data:
    driver: local
networks:
  app-default-net:
    driver: bridge

